### ISSUE TITLE
dtype for millis should be unsigned long

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#26] opened 2020-05-16 16:00 UTC
We should use unsigned long for all millis variables, or uint32_t

I don't understand the distinction

**Comment by mwittgen** [comment] 2020-05-16 16:34
It's matter of taste. unsigned long and uint32_t on the Arduino are the same size int. In general using stdint types is more portable.

**Comment by mwittgen** [comment] 2020-05-16 19:04
duplicate of issue #24

**Closed by mwittgen** 2020-05-16 19:04 UTC
